# Generated by Django 4.2.3 on 2023-07-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='end_weight',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='start_weight',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='workouts',
            field=models.ManyToManyField(to='workouts.workout'),
        ),
        migrations.DeleteModel(
            name='ExerciseRecord',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
